#########
######### BEFORE ANY CHANGES, MAKE SURE TO CHECK THE DOCS
######### https://github.com/actions/labeler
#########


automations:
- automations/**

workflows:
- .github/**

website:
- docs/**

homelab:
- homelab/**
