name: Labeler
on:
  pull_request:
    branches:
      - main

jobs:
  label:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yaml

  
